spring.application.name=cherry
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=msdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=myStrong#Password1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update