spring.application.name=cherry
spring.datasource.url=jdbc:postgresql://${RDS_ENDPOINT}:5432/cherry
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
cors.allowed-origins=https://d7ylbzptbyrhn.cloudfront.net,https://cherry.joshroundy.dev,http://localhost:3000
frontend.url=https://cherry.joshroundy.dev

# HTTPS Configuration
server.ssl.key-store=${KEYSTORE_PATH}
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

# Increase the maximum file size for uploads
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB
# Increase the maximum HTTP header size
server.max-http-request-header-size=1MB