spring.application.name=cherry
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CherryDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=username
spring.datasource.password=P4ssw0rd$good
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
openai_api_key=${OPENAI_API_KEY}
cors.allowed-origins=http://localhost:3000,http://localhost:3000/
frontend.url=http://localhost:3000

# Recaptcha Configuration
recaptcha.secret.key=${RECAPTCHA_SECRET_KEY}

# Email configuration
spring.mail.host=smtp.porkbun.com
spring.mail.port=587
spring.mail.username=cherry@joshroundy.dev
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true